In [80]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN, KMeans, SpectralClustering
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

df=pd.read_csv("drug200.csv")
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [81]:
print(df.isnull().sum())

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [82]:
df.dtypes

Age              int64
Sex             object
BP              object
Cholesterol     object
Na_to_K        float64
Drug            object
dtype: object

In [83]:
df=pd.get_dummies(df,columns=['Sex','BP','Cholesterol'],drop_first=True)

In [84]:
df.head()

   Age  Na_to_K   Drug  Sex_M  BP_LOW  BP_NORMAL  Cholesterol_NORMAL
0   23   25.355  drugY  False   False      False               False
1   47   13.093  drugC   True    True      False               False
2   47   10.114  drugC   True    True      False               False
3   28    7.798  drugX  False   False       True               False
4   61   18.043  drugY  False    True      False               False

In [85]:
df=df.drop(columns=['Na_to_K'])

In [86]:
# bins=[0,20,40,100]
# age=['junior','adult','senior','old']
# df['age_cat']=pd.cut(df['Age'],bins,age)

In [87]:
# df=pd.get_dummies(df,columns=['age_cat'],drop_first=True)

In [88]:
df.head()

   Age   Drug  Sex_M  BP_LOW  BP_NORMAL  Cholesterol_NORMAL
0   23  drugY  False   False      False               False
1   47  drugC   True    True      False               False
2   47  drugC   True    True      False               False
3   28  drugX  False   False       True               False
4   61  drugY  False    True      False               False

In [89]:
X=df.drop(columns=['Drug'])

In [96]:
km=KMeans(n_clusters=5)
ss=StandardScaler()
X=ss.fit_transform(X)

In [97]:
df['cluster']=km.fit_predict(X)

In [98]:
df.head()

,Age,Drug,Sex_M,BP_LOW,BP_NORMAL,Cholesterol_NORMAL,cluster,cluster_db,cluster_spec
0,23,drugY,False,False,False,False,0,0,1
1,47,drugC,True,True,False,False,4,1,4
2,47,drugC,True,True,False,False,4,1,4
3,28,drugX,False,False,True,False,1,2,1
4,61,drugY,False,True,False,False,2,3,6

In [99]:
print(silhouette_score(X,df['cluster']))

0.31904981011012395

In [100]:
db=DBSCAN(eps=1.5,min_samples=5)
df['cluster_db']=db.fit_predict(X)

print(silhouette_score(X,df['cluster_db']))

0.5149602378827224

In [101]:
sc=SpectralClustering()
df['cluster_spec']=sc.fit_predict(X)

print(silhouette_score(X,df['cluster_spec']))

0.37003404428960124